name: Build Release

on:
  push:
    branches:
      - improve-ci
    paths:
      - .github/workflows/**
      - Magearna/**
      - Michina/**
      - ONNXRuntime/**
      - Tokenizers/**
      - '!**.md'

jobs:
  build-onnxruntime:
    name: Build ONNXRuntime XCFramework
    runs-on: macos-26
    env:
      GENERATED_XCFRAMEWORK_PATH: ONNXRuntime/onnxruntime/build/onnxruntime.xcframework
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Setup Cache
        id: cache-onnxruntime
        uses: actions/cache@v6
        with:
          key: cache-onnxruntime-${{ hashFiles('ONNXRuntime/onnxruntime', 'ONNXRuntime/Scripts/**') }}
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}
      - name: Setup Build Cache
        id: cache-onnxruntime-build
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        uses: actions/cache@v6
        with:
          key: cache-onnxruntime-build-${{ hashFiles('ONNXRuntime/onnxruntime') }}
          path: ONNXRuntime/onnxruntime/build
      - name: Build
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        env:
          ORT_UPDATE_CMAKE: ${{ case(steps.cache-onnxruntime-build.outputs.cache-hit != 'true', true, '') }}
        run: ONNXRuntime/Scripts/build-onnxruntime.sh
      - name: Archive
        run: aa archive -D ${{ env.GENERATED_XCFRAMEWORK_PATH }} -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          archive: false

  build-tokenizers:
    name: Build Tokenizers XCFramework
    runs-on: macos-26
    env:
      GENERATED_XCFRAMEWORK_PATH: Tokenizers/Rust/target/tokenizers.xcframework
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Cache
        id: cache-tokenizers
        uses: actions/cache@v6
        with:
          key: cache-tokenizers-${{ hashFiles('Tokenizers/Rust/Cargo.lock', 'Tokenizers/Rust/src/**', 'Tokenizers/Scripts/**') }}
          path: |
            ${{ env.GENERATED_XCFRAMEWORK_PATH }}
            Tokenizers/Sources/Tokenizers/*bridge.rs.*
      - name: Setup Tools
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: cargo install --version 1.0.194 cxxbridge-cmd
      - name: Build
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: Tokenizers/Scripts/build-tokenizers.sh
      - name: Archive
        run: |
          aa archive -D ${{ env.GENERATED_XCFRAMEWORK_PATH }} -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          aa archive -D Tokenizers/Sources/Tokenizers -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.generated-sources.aar \
            -include-regex 'bridge.rs.'
      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          archive: false
      - name: Upload Additional Sources
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.generated-sources.aar
          archive: false

  build-machina:
    name: Build Machina
    runs-on: macos-26
    needs:
      - build-onnxruntime
      - build-tokenizers
    env:
      XCODE_WORKSPACE: ${{ github.workspace }}/Michina.xcworkspace
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Prepare Paths
        id: paths
        env:
          ARTIFACTS_PATH: ${{ runner.temp }}/Artifacts
          DERIVED_DATA_PATH: ${{ runner.temp }}/DerivedData
          SECRETS_PATH: ${{ runner.temp }}/Secrets
        run: |
          mkdir -p ${{ env.ARTIFACTS_PATH }}
          echo "artifacts=${{ env.ARTIFACTS_PATH }}" >> $GITHUB_OUTPUT

          mkdir -p ${{ env.DERIVED_DATA_PATH }}
          echo "derived-data=${{ env.DERIVED_DATA_PATH }}" >> $GITHUB_OUTPUT

          mkdir -p ${{ env.SECRETS_PATH }}
          echo "secrets=${{ env.SECRETS_PATH }}" >> $GITHUB_OUTPUT

      - name: Download ONNXRuntime XCFramework
        uses: actions/download-artifact@v8
        with:
          name: onnxruntime.xcframework.aar
          path: ${{ steps.paths.outputs.artifacts }}
      - name: Download Tokenizers XCFramework
        uses: actions/download-artifact@v8
        with:
          name: tokenizers.xcframework.aar
          path: ${{ steps.paths.outputs.artifacts }}
      - name: Download Tokenizers Generated Sources
        uses: actions/download-artifact@v8
        with:
          name: tokenizers.xcframework.generated-sources.aar
          path: ${{ steps.paths.outputs.artifacts }}
      - name: Extract Artifacts
        run: |
          mkdir -p ONNXRuntime/onnxruntime/build
          aa extract -i ${{ steps.paths.outputs.artifacts }}/onnxruntime.xcframework.aar -d ONNXRuntime/onnxruntime/build

          mkdir -p Tokenizers/Rust/target
          aa extract -i ${{ steps.paths.outputs.artifacts }}/tokenizers.xcframework.aar -d Tokenizers/Rust/target
          aa extract -i ${{ steps.paths.outputs.artifacts }}/tokenizers.xcframework.generated-sources.aar -d Tokenizers/Sources

      - name: Setup Xcode Certificate
        env:
          DEVELOPER_ID_CERTIFICATE_PATH: ${{ steps.paths.outputs.secrets }}/developer-id.p12
          KEYCHAIN_PATH: ${{ steps.paths.outputs.secrets }}/build.keychain
        run: |
          echo -n ${{ secrets.XCODE_DEVELOPER_ID_CERTIFICATE }} | base64 --decode -o ${{ env.DEVELOPER_ID_CERTIFICATE_PATH }}

          KEYCHAIN_PASSWORD=$(openssl rand -base64 12)

          security create-keychain -p $KEYCHAIN_PASSWORD ${{ env.KEYCHAIN_PATH }}
          security unlock-keychain -p $KEYCHAIN_PASSWORD ${{ env.KEYCHAIN_PATH }}

          security import ${{ env.DEVELOPER_ID_CERTIFICATE_PATH }} -k ${{ env.KEYCHAIN_PATH }}  \
            -t cert -f pkcs12 -P ${{ secrets.XCODE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}         \
            -A
          security set-key-partition-list -S apple-tool:,apple: ${{ env.KEYCHAIN_PATH }}
          security list-keychain -d user -s ${{ env.KEYCHAIN_PATH }}

      - name: Manage Build Number
        run: |
          echo "Set build number to ${{ github.run_number }}"
          sed -i '' 's/CURRENT_PROJECT_VERSION = .*/CURRENT_PROJECT_VERSION = ${{ github.run_number }};/g' \
            Michina/Michina.xcodeproj/project.pbxproj

      - name: Prepare Packages
        run: |
          Magearna/Scripts/prepare-proto.sh

          SPM_SECURITY_PATH=~/Library/org.swift.swiftpm/security
          mkdir -p $SPM_SECURITY_PATH
          cp ci_scripts/ci_post_clone/Security/plugins.json $SPM_SECURITY_PATH

      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies                      \
            -workspace ${{ env.XCODE_WORKSPACE }}                     \
            -derivedDataPath ${{ steps.paths.outputs.derived-data }}  \
            -scheme Michina                                           \
            -hideShellScriptEnvironment

      - name: Archive
        id: archive
        env:
          ARCHIVE_PATH: ${{ runner.temp }}/Michina.xcarchive
        run: |
          xcodebuild archive                                          \
            -workspace ${{ env.XCODE_WORKSPACE }}                     \
            -scheme Michina -destination generic/platform=macOS       \
            -archivePath ${{ env.ARCHIVE_PATH }}                      \
            -derivedDataPath ${{ steps.paths.outputs.derived-data }}  \
            -hideShellScriptEnvironment
          
          echo "archive-path=${{ env.ARCHIVE_PATH }}" >> $GITHUB_OUTPUT

      - name: Export for App Store Connect
        id: export-app-store-connect
        env:
          EXPORT_PATH: ${{ runner.temp }}/Exports/app-store-connect
          EXPORT_OPTIONS_PATH: ${{ runner.temp }}/Exports/app-store-connect.plist
        run: |
          mkdir -p ${{ env.EXPORT_OPTIONS_PATH }}
          plutil -create xml1 ${{ env.EXPORT_OPTIONS_PATH }}
          plutil -insert method -string app-store-connect ${{ env.EXPORT_OPTIONS_PATH }}

          xcodebuild -exportArchive                                 \
            -archivePath ${{ steps.archive.outputs.archive-path }}  \
            -exportPath ${{ env.EXPORT_PATH }}                      \
            -exportOptionsPlist ${{ env.EXPORT_OPTIONS_PATH }}      \
            -hideShellScriptEnvironment

          echo "export-path=${{ env.EXPORT_OPTIONS_PATH }}" >> $GITHUB_OUTPUT

      - name: Export for Developer ID
        id: export-developer-id
        env:
          EXPORT_PATH: ${{ runner.temp }}/Exports/developer-id
          EXPORT_OPTIONS_PATH: ${{ runner.temp }}/Exports/developer-id.plist
        run: |
          mkdir -p ${{ env.EXPORT_OPTIONS_PATH }}
          plutil -create xml1 ${{ env.EXPORT_OPTIONS_PATH }}
          plutil -insert method -string developer-id ${{ env.EXPORT_OPTIONS_PATH }}

          xcodebuild -exportArchive                                 \
            -archivePath ${{ steps.archive.outputs.archive-path }}  \
            -exportPath ${{ env.EXPORT_PATH }}                      \
            -exportOptionsPlist ${{ env.EXPORT_OPTIONS_PATH }}      \
            -hideShellScriptEnvironment
          
          echo "export-path=${{ env.EXPORT_OPTIONS_PATH }}" >> $GITHUB_OUTPUT

      - name: Notarize
        env:
          APP_STORE_CONNECT_API_KEY_PATH: ${{ steps.paths.outputs.secrets }}/app-store-connect-api.p8
          APP_PATH: ${{ steps.export-developer-id.outputs.export-path }}/Michina.app
        run: |
          echo -n ${{ secrets.APP_STORE_CONNECT_API_KEY }} | base64 --decode -o ${{ env.APP_STORE_CONNECT_API_KEY_PATH }}

          ditto -c -k --keepParent ${{ env.APP_PATH }} ${{ env.APP_PATH }}.zip
          xcrun notarytool submit ${{ env.APP_PATH }}.zip         \
            --key ${{ env.APP_STORE_CONNECT_API_KEY_PATH }}       \
            --key-id ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}  \
            --wait
          xcrun stapler staple ${{ env.APP_PATH }}
          rm ${{ env.APP_PATH }}.zip

      - name: Upload Archive
        uses: actions/upload-artifact@v7
        with:
          name: Michina.xcarchive
          path: ${{ steps.archive.outputs.archive-path }}
      - name: Upload App Store Connect Archive
        uses: actions/upload-artifact@v7
        with:
          name: Michina-App-Store-Connect
          path: ${{ steps.export-app-store-connect.outputs.export-path }}
      - name: Upload Developer ID Archive
        uses: actions/upload-artifact@v7
        with:
          name: Michina-Developer-ID
          path: ${{ steps.export-developer-id.outputs.export-path }}
