name: Build Distribution

on:
  push:
    branches:
      - main
    paths:
      - Magearna/**
      - Michina/**
      - ONNXRuntime/**
      - Tokenizers/**
      - '!**.md'
  workflow_dispatch:

jobs:
  build-xcframeworks:
    name: Build XCFrameworks
    uses: ./.github/workflows/build-xcframeworks.yml

  build-machina:
    name: Build Michina
    runs-on: macos-26
    needs:
      - build-xcframeworks
    env:
      XCODE_WORKSPACE: ${{ github.workspace }}/Michina.xcworkspace
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Xcode Cache
        id: cache-tokenizers
        uses: actions/cache@v6
        with:
          key: cache-xcode
          path: DerivedData

      - name: Install Tools
        run: |
          gem install xcpretty
          brew install git-tools

      - name: Prepare Paths
        id: paths
        env:
          ARTIFACTS_PATH: ${{ runner.temp }}/Artifacts
          DERIVED_DATA_PATH: ${{ github.workspace }}/DerivedData
          EXPORTS_PATH: ${{ runner.temp }}/Exports
          SECRETS_PATH: ${{ runner.temp }}/Secrets
        run: |
          mkdir -p ${{ env.ARTIFACTS_PATH }}
          echo 'artifacts=${{ env.ARTIFACTS_PATH }}' >> $GITHUB_OUTPUT

          mkdir -p ${{ env.DERIVED_DATA_PATH }}
          echo 'derived-data=${{ env.DERIVED_DATA_PATH }}' >> $GITHUB_OUTPUT

          mkdir -p ${{ env.EXPORTS_PATH }}
          echo 'exports=${{ env.EXPORTS_PATH }}' >> $GITHUB_OUTPUT

          mkdir -p ${{ env.SECRETS_PATH }}
          echo 'secrets=${{ env.SECRETS_PATH }}' >> $GITHUB_OUTPUT

      - name: Restore ONNXRuntime XCFrameworks Cache
        uses: actions/cache@v6
        with:
          key: ${{ needs.build-xcframeworks.outputs.onnxruntime }}
          path: ONNXRuntime/Frameworks/onnxruntime/onnxruntime.xcframework
          fail-on-cache-miss: true

      - name: Restore Tokenizers XCFrameworks Cache
        uses: actions/cache@v6
        with:
          key: ${{ needs.build-xcframeworks.outputs.tokenizers }}
          path: |
            Tokenizers/Frameworks/tokenizers/tokenizers.xcframework
            Tokenizers/Sources/Tokenizers/*bridge.rs.*
          fail-on-cache-miss: true

      - name: Setup Secrets
        id: secrets
        env:
          MAC_DEVELOPMENT_CERTIFICATE_PATH: ${{ steps.paths.outputs.secrets }}/mac-development.p12
          DEVELOPER_ID_CERTIFICATE_PATH: ${{ steps.paths.outputs.secrets }}/developer-id.p12
          APPLE_DISTRIBUTION_CERTIFICATE_PATH: ${{ steps.paths.outputs.secrets }}/apple-distribution.p12
          MAC_INSTALLER_DISTRIBUTION_CERTIFICATE_PATH: ${{ steps.paths.outputs.secrets }}/mac-installer-distribution.p12
          KEYCHAIN_PATH: ${{ steps.paths.outputs.secrets }}/build.keychain

          APP_STORE_CONNECT_API_KEY_PATH: >
            ${{ steps.paths.outputs.secrets }}/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
        run: |
          KEYCHAIN_PASSWORD=$(openssl rand -base64 12)

          security create-keychain -p $KEYCHAIN_PASSWORD ${{ env.KEYCHAIN_PATH }}
          security set-keychain-settings -lut 21600 ${{ env.KEYCHAIN_PATH }}
          security unlock-keychain -p $KEYCHAIN_PASSWORD ${{ env.KEYCHAIN_PATH }}

          echo -n ${{ secrets.XCODE_MAC_DEVELOPMENT_CERTIFICATE }}            \
            | base64 --decode -o ${{ env.MAC_DEVELOPMENT_CERTIFICATE_PATH }}
          security import ${{ env.MAC_DEVELOPMENT_CERTIFICATE_PATH }}     \
            -P ${{ secrets.XCODE_MAC_DEVELOPMENT_CERTIFICATE_PASSWORD }}  \
            -t cert -f pkcs12                                             \
            -A -k ${{ env.KEYCHAIN_PATH }}

          echo -n ${{ secrets.XCODE_DEVELOPER_ID_CERTIFICATE }}           \
            | base64 --decode -o ${{ env.DEVELOPER_ID_CERTIFICATE_PATH }}
          security import ${{ env.DEVELOPER_ID_CERTIFICATE_PATH }}    \
            -P ${{ secrets.XCODE_DEVELOPER_ID_CERTIFICATE_PASSWORD }} \
            -t cert -f pkcs12                                         \
            -A -k ${{ env.KEYCHAIN_PATH }}

          echo -n ${{ secrets.XCODE_APPLE_DISTRIBUTION_CERTIFICATE }}           \
            | base64 --decode -o ${{ env.APPLE_DISTRIBUTION_CERTIFICATE_PATH }}
          security import ${{ env.APPLE_DISTRIBUTION_CERTIFICATE_PATH }}    \
            -P ${{ secrets.XCODE_APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }} \
            -t cert -f pkcs12                                               \
            -A -k ${{ env.KEYCHAIN_PATH }}
          
          echo -n ${{ secrets.XCODE_MAC_INSTALLER_DISTRIBUTION_CERTIFICATE }}           \
            | base64 --decode -o ${{ env.MAC_INSTALLER_DISTRIBUTION_CERTIFICATE_PATH }}
          security import ${{ env.MAC_INSTALLER_DISTRIBUTION_CERTIFICATE_PATH }}    \
            -P ${{ secrets.XCODE_MAC_INSTALLER_DISTRIBUTION_CERTIFICATE_PASSWORD }} \
            -t cert -f pkcs12                                                       \
            -A -k ${{ env.KEYCHAIN_PATH }}

          security set-key-partition-list -S apple-tool:,apple: ${{ env.KEYCHAIN_PATH }}
          security list-keychain -d user -s ${{ env.KEYCHAIN_PATH }}

          echo -n ${{ secrets.APP_STORE_CONNECT_API_KEY }}                  \
            | base64 --decode -o ${{ env.APP_STORE_CONNECT_API_KEY_PATH }}
          echo 'app-store-connect-api-key-path=${{ env.APP_STORE_CONNECT_API_KEY_PATH }}' >> $GITHUB_OUTPUT

      - name: Manage Build Number
        id: version
        env:
          XCODE_PROJECT_FILE: Michina/Michina.xcodeproj/project.pbxproj
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo 'Set build number to ${{ env.BUILD_NUMBER }}'
          sed -i '' 's/CURRENT_PROJECT_VERSION = .*/CURRENT_PROJECT_VERSION = ${{ env.BUILD_NUMBER }};/g' \
            ${{ env.XCODE_PROJECT_FILE }}
          MARKETING_VERSION=$(                                                                            \
            sed -nE 's/\t+MARKETING_VERSION = ([0-9\.]+);/\1/p' ${{ env.XCODE_PROJECT_FILE }} | head -n 1 \
          )

          echo "version=$MARKETING_VERSION" >> $GITHUB_OUTPUT
          echo 'build=${{ env.BUILD_NUMBER }}' >> $GITHUB_OUTPUT

      - name: Prepare Packages
        run: |
          Magearna/Scripts/prepare-proto.sh

          SPM_SECURITY_PATH=~/Library/org.swift.swiftpm/security
          mkdir -p $SPM_SECURITY_PATH
          cp .github/security/plugins.json $SPM_SECURITY_PATH

      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies                      \
            -workspace ${{ env.XCODE_WORKSPACE }}                     \
            -derivedDataPath ${{ steps.paths.outputs.derived-data }}  \
            -scheme Michina                                           \
            -onlyUsePackageVersionsFromResolvedFile                   \
            -hideShellScriptEnvironment

      - name: Restore Modification Time
        env:
          CHECKOUTS_PATH: ${{ steps.paths.outputs.derived-data }}/SourcePackages/checkouts
        run: |
          git restore-mtime
          for path in ${{ env.CHECKOUTS_PATH }}/*
          do
            git restore-mtime -C $path
          done
          defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Archive
        id: archive
        env:
          ARCHIVE_PATH: ${{ runner.temp }}/Michina.xcarchive
        # FIXME: xcodebuild still compiles lot of files with cached derived data
        run: |
          set -o pipefail

          xcodebuild archive                                          \
            -workspace ${{ env.XCODE_WORKSPACE }}                     \
            -scheme Michina                                           \
            -destination generic/platform=macOS                       \
            -archivePath ${{ env.ARCHIVE_PATH }}                      \
            -derivedDataPath ${{ steps.paths.outputs.derived-data }}  \
            COMPILATION_CACHE_ENABLE_CACHING=1                        \
            -hideShellScriptEnvironment                               \
            | xcpretty

          ditto -c -k --keepParent ${{ env.ARCHIVE_PATH }} ${{ env.ARCHIVE_PATH }}.zip
          echo 'archive-path=${{ env.ARCHIVE_PATH }}' >> $GITHUB_OUTPUT

      - name: Export and Notarize App for Developer ID
        id: export-developer-id
        background: true
        env:
          EXPORT_OPTIONS_PATH: ${{ steps.paths.outputs.exports }}/developer-id.plist
          EXPORT_PATH: ${{ steps.paths.outputs.exports }}/developer-id
          APP_PATH: ${{ steps.paths.outputs.exports }}/developer-id/Michina.app
        run: |
          set -o pipefail

          plutil -create xml1 ${{ env.EXPORT_OPTIONS_PATH }}
          plutil -insert method -string developer-id ${{ env.EXPORT_OPTIONS_PATH }}

          mkdir -p ${{ env.EXPORT_PATH }}
          xcodebuild -exportArchive                                 \
            -archivePath ${{ steps.archive.outputs.archive-path }}  \
            -exportPath ${{ env.EXPORT_PATH }}                      \
            -exportOptionsPlist ${{ env.EXPORT_OPTIONS_PATH }}      \
            -hideShellScriptEnvironment                             \
            | xcpretty

          ditto -c -k --keepParent ${{ env.APP_PATH }} ${{ env.APP_PATH }}.zip
          xcrun notarytool submit ${{ env.APP_PATH }}.zip                     \
            --key ${{ steps.secrets.outputs.app-store-connect-api-key-path }} \
            --key-id ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}              \
            --issuer ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}       \
            --wait
          xcrun stapler staple ${{ env.APP_PATH }}
          rm ${{ env.APP_PATH }}.zip

          ditto -c -k --keepParent ${{ env.EXPORT_PATH }} ${{ env.EXPORT_PATH }}.zip
          echo 'export-path=${{ env.EXPORT_PATH }}' >> $GITHUB_OUTPUT

      - name: Export and Upload Package to App Store Connect
        id: export-app-store-connect
        background: true
        timeout-minutes: 20
        env:
          API_PRIVATE_KEYS_DIR: ${{ steps.paths.outputs.secrets }}
          EXPORT_OPTIONS_PATH: ${{ steps.paths.outputs.exports }}/app-store-connect.plist
          EXPORT_PATH: ${{ steps.paths.outputs.exports }}/app-store-connect
        run: |
          set -o pipefail

          plutil -create xml1 ${{ env.EXPORT_OPTIONS_PATH }}
          plutil -insert method -string app-store-connect ${{ env.EXPORT_OPTIONS_PATH }}

          mkdir -p ${{ env.EXPORT_PATH }}
          xcodebuild -exportArchive                                                             \
            -archivePath ${{ steps.archive.outputs.archive-path }}                              \
            -exportPath ${{ env.EXPORT_PATH }}                                                  \
            -exportOptionsPlist ${{ env.EXPORT_OPTIONS_PATH }}                                  \
            -allowProvisioningUpdates                                                           \
            -authenticationKeyPath ${{ steps.secrets.outputs.app-store-connect-api-key-path }}  \
            -authenticationKeyID ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}                    \
            -authenticationKeyIssuerID ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}       \
            -hideShellScriptEnvironment                                                         \
            | xcpretty

          xcrun altool --upload-package ${{ env.EXPORT_PATH }}/Michina.pkg  \
            --platform macos --wait                                         \
            --api-key ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}           \
            --api-issuer ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}

          echo 'export-path=${{ env.EXPORT_PATH }}' >> $GITHUB_OUTPUT

      - wait:
          - export-app-store-connect

      - name: Collect and Upload App Store Text
        background: true
        continue-on-error: true
        env:
          API_PRIVATE_KEYS_DIR: ${{ steps.paths.outputs.secrets }}
          APP_STORE_TEXT_PATH: ${{ steps.paths.outputs.exports }}/app-store-connect/AppStore
          APP_IDENTIFIER: dev.lucka.Michina
        # FIXME: xcrun altool --beta-app-store-text doesn't actually work
        run: |
          sleep 30s

          testFlightTextDirectory=${{ env.APP_STORE_TEXT_PATH }}/beta-${{ env.APP_IDENTIFIER }}/upload/MACOS
          mkdir -p $testFlightTextDirectory

          for localization in AppStoreConnect/TestFlight/*
          do
            textFile=$testFlightTextDirectory/$(basename $localization).txt
            touch $textFile
            echo "\"whatsNew\" = \"$(sed 's/"/\\"/g' $localization/changelog.txt)\";" >> $textFile
          done

          xcrun altool --beta-app-store-text ${{ env.APP_STORE_TEXT_PATH }} --upload  \
            --apple-id ${{ env.APP_IDENTIFIER }} --platform macos                     \
            --bundle-short-version-string '${{ steps.version.outputs.version }}'      \
            --bundle-version '${{ steps.version.outputs.build }}'                     \
            --api-key ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}                     \
            --api-issuer ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}

      - wait-all:

      - name: Upload Archive
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.archive.outputs.archive-path }}.zip
          archive: false
      - name: Upload Developer ID Archive
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.export-developer-id.outputs.export-path }}.zip
          archive: false
      - name: Upload App Store Connect Archive
        uses: actions/upload-artifact@v7
        with:
          name: app-store-connect
          path: ${{ steps.export-app-store-connect.outputs.export-path }}
