name: Build Release

on:
  push:
    branches:
      - improve-ci
    paths:
      - .github/workflows/**
      - Magearna/**
      - Michina/**
      - ONNXRuntime/**
      - Tokenizers/**
      - '!**.md'

jobs:
  build-onnxruntime:
    name: Build ONNXRuntime XCFramework
    runs-on: macos-26
    env:
      GENERATED_XCFRAMEWORK_PATH: ONNXRuntime/onnxruntime/build/onnxruntime.xcframework
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Setup Cache
        id: cache-onnxruntime
        uses: actions/cache@v6
        with:
          key: cache-onnxruntime-${{ hashFiles('ONNXRuntime/onnxruntime', 'ONNXRuntime/Scripts/**') }}
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}
      - name: Setup Build Cache
        id: cache-onnxruntime-build
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        uses: actions/cache@v6
        with:
          key: cache-onnxruntime-buid
          path: ONNXRuntime/onnxruntime/build
      - name: Build
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        env:
          ORT_UPDATE_CMAKE: true
        run: ONNXRuntime/Scripts/build-onnxruntime.sh
      - name: Archive
        run: aa archive -D ${{ env.GENERATED_XCFRAMEWORK_PATH }} -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          archive: false

  build-tokenizers:
    name: Build Tokenizers XCFramework
    runs-on: macos-26
    env:
      GENERATED_XCFRAMEWORK_PATH: Tokenizers/Rust/target/tokenizers.xcframework
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Cache
        id: cache-tokenizers
        uses: actions/cache@v6
        with:
          key: cache-tokenizers-${{ hashFiles('Tokenizers/Rust/Cargo.lock', 'Tokenizers/Rust/src/**', 'Tokenizers/Scripts/**') }}
          path: |
            ${{ env.GENERATED_XCFRAMEWORK_PATH }}
            Tokenizers/Sources/Tokenizers/*bridge.rs.*
      - name: Setup Tools
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: cargo install --version 1.0.194 cxxbridge-cmd
      - name: Build
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: Tokenizers/Scripts/build-tokenizers.sh
      - name: Archive
        run: |
          aa archive -D ${{ env.GENERATED_XCFRAMEWORK_PATH }} -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          aa archive -D Tokenizers/Sources/Tokenizers -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.generated-sources.aar \
            -include-regex 'bridge.rs.'
      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          archive: false
      - name: Upload Additional Sources
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.generated-sources.aar
          archive: false
