name: Build XCFrameworks

on:
  workflow_call:
    outputs:
      onnxruntime:
        value: ${{ jobs.build-onnxruntime.outputs.cache-key }}
      tokenizers:
        value: ${{ jobs.build-tokenizers.outputs.cache-key }}

jobs:
  build-onnxruntime:
    name: Build ONNXRuntime XCFramework
    runs-on: macos-26
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    env:
      GENERATED_XCFRAMEWORK_PATH: ONNXRuntime/Frameworks/onnxruntime/onnxruntime.xcframework
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Generate Cache Key
        id: cache-key
        env:
          KEY_HASH: ${{ hashFiles('ONNXRuntime/Frameworks/onnxruntime/**') }}
        run: echo 'key=cache-onnxruntime-${{ env.KEY_HASH }}' >> $GITHUB_OUTPUT

      - name: Setup Cache
        id: cache-onnxruntime
        uses: actions/cache@v6
        with:
          key: ${{ steps.cache-key.outputs.key }}
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}
      - name: Setup Build Cache
        id: cache-onnxruntime-build
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        uses: actions/cache@v6
        with:
          key: cache-onnxruntime-build
          path: ONNXRuntime/Frameworks/onnxruntime/source/build
      - name: Build
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        env:
          ORT_UPDATE_CMAKE: true
        run: ONNXRuntime/Frameworks/onnxruntime/build.sh

      - name: Archive
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        run: aa archive -D ${{ env.GENERATED_XCFRAMEWORK_PATH }} -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar

      - name: Upload XCFramework
        id: upload-xcframework
        if: steps.cache-onnxruntime.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          archive: false

  build-tokenizers:
    name: Build Tokenizers XCFramework
    runs-on: macos-26
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    env:
      GENERATED_XCFRAMEWORK_PATH: Tokenizers/Frameworks/tokenizers/tokenizers.xcframework
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Generate Cache Keys
        id: cache-key
        env:
          KEY_HASH: ${{ hashFiles('Tokenizers/Frameworks/tokenizers/**') }}
        run: echo 'key=cache-tokenizers-${{ env.KEY_HASH }}' >> $GITHUB_OUTPUT

      - name: Setup Cache
        id: cache-tokenizers
        uses: actions/cache@v6
        with:
          key: ${{ steps.cache-key.outputs.key }}
          path: |
            ${{ env.GENERATED_XCFRAMEWORK_PATH }}
            Tokenizers/Sources/Tokenizers/*bridge.rs.*

      - name: Setup Tools
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: cargo install --version 1.0.194 cxxbridge-cmd
      - name: Build
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: Tokenizers/Frameworks/tokenizers/build.sh

      - name: Archive
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        run: |
          aa archive -D ${{ env.GENERATED_XCFRAMEWORK_PATH }} -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          aa archive -D Tokenizers/Sources/Tokenizers -o ${{ env.GENERATED_XCFRAMEWORK_PATH }}.generated-sources.aar \
            -include-regex 'bridge.rs.'

      - name: Upload XCFramework
        id: upload-xcframework
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.aar
          archive: false
      - name: Upload Additional Sources
        id: upload-generated-sources
        if: steps.cache-tokenizers.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.GENERATED_XCFRAMEWORK_PATH }}.generated-sources.aar
          archive: false
